apiVersion: v1
kind: Namespace
metadata:
  name: memo-app
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: memo-app
type: Opaque
data:
  JWT_SECRET: c3VwZXJzZWNyZXQ=
